### ISSUE TITLE
Radio buttons pro vybrání roční/měsíční/denní/hodinový mzdy pro graf

### ISSUE THREAD

**Issue by inson1** [zakjan/czech-income-tax-calculator#15]

**Comment by inson1** [comment]
Tohle je pro mě nejdůležitější imho

**Comment by zakjan** [comment]
Tomu bych se raději vyhnul, protože to nezohledňuje některé částky se platí jen ročně (po podání přiznání/přehledů) nebo pololetně/čtvrtletně (zálohy na daň z příjmů). Cíl kalkulačky je porovnání celkových nákladů, ne měsíční rozpis.

**Comment by inson1** [comment]
@zakjan Takové částky by měli být rozepsány s stejným dílem do měsíců, je fajn vidět náklady vs čistou mzdu za měsíc, hodinu atd.

Normálnímu člověku nic nedá, nebo málo, se to dozvědět za rok.
