### ISSUE TITLE
[BUG] Špatnej výpočet při vyšších mzdách

### ISSUE THREAD

**Issue by inson1** [zakjan/czech-income-tax-calculator#23]
Ale mimo #22 nevím v čem dalším může být ta chyba a určitě nebude jenom to v tom
https://www.vypocet.cz/cista-mzda
https://www.penize.cz/kalkulacky/vypocet-ciste-mzdy#mzda-vypocet (taky chybí #22)
![image](https://github.com/zakjan/czech-income-tax-calculator/assets/75314629/15c6a1a6-9ab4-458e-8633-7e701bc932ca)

**Comment by inson1** [comment]
Ale máš ho tam, takže špatnej výpočet?
![image](https://github.com/zakjan/czech-income-tax-calculator/assets/75314629/24d9b85a-2621-4b45-825e-e3489e09d851)

**Comment by zakjan** [comment]
Zohlednění ve výpočtu je zde. https://github.com/zakjan/czech-income-tax-calculator/blob/master/src/services/taxCalculator.js#L43

Jde o vyměřovací základ, ne výslednou hodnotu.

Když násobně zvyšuju příjmy (přidávání 0 na konec), je vidět že sociální má maximální hodnotu, zdravotní je neomezené.

**Comment by zakjan** [comment]
Jinak díky za všechny podněty, PR jsou vítané ;)

**Comment by inson1** [comment]
@zakjan To pořád nevysvětluje proč to nevychází stejně jako ostatní kalkulačky, tohle byla moje hypotéza proč, ale očividně mylná

**Comment by zakjan** [comment]
Není to tím že jiné kalkulačky počítají jen s měsíčními částkami, takže nemůžou zohlednit roční limity?

**Comment by inson1** [comment]
Já bych řekl, že roční limity některé kalkulačky zohledňují, někdy to pořádně prozkoumám proč ty hodnoty jinné.

**Comment by inson1** [comment]
@zakjan Už vím, kde je chyba. Soliární daň máš 22% = má být 23%

**Comment by zakjan** [comment]
Aha, díky!

**Comment by inson1** [comment]
sorry for spam, just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
