### ISSUE TITLE
[Question] Jak hostuješ aplikaci na github pages?

### ISSUE THREAD

**Issue by inson1** [zakjan/czech-income-tax-calculator#30]
Pokud to spustím z masteru, tak se mi otevře Readme
https://inson1.github.io/czech-income-tax-calculator/
Nebo tohle
https://inson1.github.io/czech-income-tax-calculator/src/

A docs nefungují. A nic jiného vybrat nemůžu

Github actions taky nemáš ..... Tak kde dělám chybu @zakjan ?

Děkuju předem za odpovědět.

**Comment by zakjan** [comment]
Nijak, tohle repo existuje dřív než GitHub Actions. Hostuju na Vercelu. Díky tomu jsou v PR preview deployment linky.

**Comment by inson1** [comment]
@zakjan Tak to potom jo
