### ISSUE TITLE
Default values for employees and contractors should be different

### ISSUE THREAD

**Issue by inson1** [zakjan/czech-income-tax-calculator#38]
Options how to fix it
1) Different static options
2) Automatic calculation from cost of the employer for employee

**Comment by zakjan** [comment]
Tady si dovolím nesouhlasit. Princip téhle kalkulačky je porovnávání celkových nákladů. To že máme odvody rozdělené na část kterou platí zaměstnavatel vs. zaměstnanec, a že se vyjednává hrubá mzda bez zaměstnavatelské části odvodů, mi přijde jako historický nesmysl. Zajímalo by mě jak to vzniklo.

**Comment by zakjan** [comment]
Teď vidím, že pro zaměstnance se vyplněná hodnota už používá jako hrubá mzda, ne superhrubá. Není to to co jsi chtěl?

**Comment by inson1** [comment]
Ne, ale částečně ano. 
Spíše jsem myslel to, že zaměstnanec má průměr 40k. To je v pohodě, to je cca průměrná mzda.
Ale aby dostal OSVČ stejné peníze musí dostat víc. Protože pro OSVČ už to jsou celkové náklady. Takže celkové náklady zaměstnavatele pro 40k u zaměstnance by měl být default pro OSVČ 
A mluvím jen defaultních hodnotách, co tam jsou pokud člověk nezadá vlastní.

**Comment by inson1** [comment]
@zakjan Ale teda bylo by zajímavé mít nad  hrubou mzdou ještě jednu sekci pro celkové náklady. Jen nvm jestli už to není moc.

**Comment by zakjan** [comment]
Rozdělil jsem diagramy, jsou vidět současně oba dva, a mají rozdělené hodnoty, aby se daly porovnávat různé vstupy.
