### ISSUE TITLE
Changes in 2024

### ISSUE THREAD

**Issue by inson1** [zakjan/czech-income-tax-calculator#40]
Hi, I' opening this issue for preparation for 2024.

**Comment by inson1** [comment]
Znovuzavedením nemocenského pojištění zaměstnanců ve výši 0,6 % Nově by se mělo nemocenské pojištění strhávat i ze zaměstnancovy části a snížit mu tak čistou mzdu.

**Comment by zakjan** [comment]
Duplicates #9

**Comment by inson1** [comment]
posun prahu pro progresivní 23% sazbu daně ze čtyřnásobku na trojnásobek průměrné mzdy

**Comment by inson1** [comment]
navýšení sazby nemocenského pojistného OSVČ o 0,6 procentního bodu (na 2,7 %)

**Comment by inson1** [comment]
@zakjan This isnt duplicate. Its preparation for the next year. So please reopen it.

**Comment by zakjan** [comment]
All done
